language: java
jdk: openjdk8
install: "./installViaTravis.sh"
script: ./gradlew -Prelease.travisci=true build --stacktrace
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
